Added Lenovo Yoga 370 and L13 Yoga
cassidyjames/oem-info pull request #6
Opened 2021-08-09 11:51 UTC by sirsleon

My small contribution to a small area of eOS :)

2021-08-09 23:29 UTC, cassidyjames requested changes
Make sure the logo path in `oem.conf` matches the filename of the image

2021-08-10 01:37 UTC, sirsleon commented
Fixed logo path

2021-08-10 02:34 UTC, cassidyjames approved these changes

2021-08-10 02:34 UTC, merged

2021-08-12 05:15 UTC, sirsleon commented
elementaryOS wouldn't load up the picture. I tried both a logo version and a laptop version. The image area would just have a 🚫 emoji.